export const mentionsData = [
  { name: "Anna Brown", id: "103", email: "anna@gmail.com" },
  { name: "John Doe", id: "101", email: "joe@gmail.com" },
  { name: "Joe Lewis", id: "102", email: "lewis@gmail.com" },
  // Add more people manually
  { name: "Alice Smith", id: "104", email: "alice@gmail.com" },
  { name: "Bob Johnson", id: "105", email: "bob@gmail.com" },
  { name: "Emily Wilson", id: "106", email: "emily@gmail.com" },
  { name: "David Lee", id: "107", email: "david@gmail.com" },
  { name: "Sarah Taylor", id: "108", email: "sarah@gmail.com" },
  { name: "Michael Brown", id: "109", email: "michael@gmail.com" },
  { name: "Jessica Martinez", id: "110", email: "jessica@gmail.com" },
  { name: "Chris Anderson", id: "111", email: "chris@gmail.com" },
  { name: "Laura Rodriguez", id: "112", email: "laura@gmail.com" },
  { name: "Daniel Harris", id: "113", email: "daniel@gmail.com" },
  { name: "Ashley Clark", id: "114", email: "ashley@gmail.com" },
  { name: "Matthew Walker", id: "115", email: "matthew@gmail.com" },
  { name: "Amanda Hall", id: "116", email: "amanda@gmail.com" },
  { name: "Kevin Young", id: "117", email: "kevin@gmail.com" },
  { name: "Elizabeth King", id: "118", email: "elizabeth@gmail.com" },
  { name: "James White", id: "119", email: "james@gmail.com" },
  { name: "Olivia Scott", id: "120", email: "olivia@gmail.com" },
];
